version: "3.5"

services:
  mysql-db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
      MYSQL_USER: anUser
      MYSQL_PASSWORD: test123
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

  api:
    image: nginx:latest
    depends_on:
      - service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://anUser:test123@mysql-db:3306/definitions?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
